name: terminus
description: "Personal security app (Project Terminus)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  location: ^8.0.1
  record: ^6.1.1
  camera: ^0.11.0+1
  flutter_background: ^1.2.0
  connectivity_plus: ^7.0.0
  http: ^1.2.1
  encrypt: ^5.0.3
  file_picker: ^10.3.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.1
  storage_space: ^1.2.0
  flutter_background_service: ^5.0.5
  google_maps_flutter: ^2.13.1
  flutter_local_notifications: ^19.4.1
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
